apiVersion: v1
kind: Template
metadata:
  name: open-liberty-builder
  annotations:
    tags: java, web app
    template.openshift.io/provider-display-name: "IBM"
    description: Just building an open liberty app
labels:
  application: open-liberty-app
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: "https://github.com/odrodrig/s2i-open-liberty"
    required: true
  - name: APP_NAME
    description: The name of the application that you would like to build.
    displayName: App name
    value: "authors2"
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: conference
    required: true
  - name: SOURCE_REPOSITORY_DIR
    description: The location within the source repo of the application
    displayName: Source Directory
    value: /web-app
    required: true
  - name: OUTPUT_DIR
    description: The location of the compiled binaries from your open liberty builder
    displayName: Output Directory
    value: /tmp/src/
    required: false
  - name: GITHUB_WEBHOOK_SECRET
    description: A secret string used to configure the GitHub webhook.
    displayName: GitHub Webhook Secret
    required: true
    from: '[a-zA-Z0-9]{10}'
    generate: expression
  - name: DOCKER_USERNAME
    description: The docker username used when tagging images
    displayName: Docker username
    required: true
    value: odrodrig
  - name: DOCKER_REGISTRY
    description: The docker registry used when tagging images
    displayName: Docker registry
    required: true
    value: docker.io
message: "... The GitHub webhook secret is ${GITHUB_WEBHOOK_SECRET} ..."
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: open-liberty-builder
  spec:
    output:
      to:
        kind: DockerImage
        name: ${DOCKER_REGISTRY}/${DOCKER_USERNAME}/authors-builder:latest
      pushSecret:
        name: regcred
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: OUTPUT_DIR
            value: ${OUTPUT_DIR}
        from:
          kind: DockerImage
          name: ${DOCKER_REGISTRY}/${DOCKER_USERNAME}/s2i-open-liberty-builder:0.1.0
        incremental: false
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
  status:
    lastVersion: 0
