apiVersion: v1
kind: Template
metadata:
  name: authors-app
  annotations:
    tags: java, web app
    template.openshift.io/provider-display-name: "IBM"
    description: Just building an open liberty app
labels:
  application: open-liberty-app
parameters:
  - name: APP_NAME
    description: The name of the application that you would like to build.
    displayName: App name
    value: "authors2"
    required: true
  - name: DOCKER_USERNAME
    description: The docker username used when tagging images
    displayName: Docker username
    required: true
    value: odrodrig
  - name: DOCKER_REGISTRY
    description: The docker registry used when tagging images
    displayName: Docker registry
    required: true
    value: docker.io
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: ${APP_NAME}
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
      spec:
        containers:
        - image: ${DOCKER_REGISTRY}/${DOCKER_USERNAME}/authors-runtime:latest
          imagePullPolicy: Always
          name: authors-runtime
          ports:
          - containerPort: 9080
            name: http
            protocol: TCP
          metadata:
            labels:
              app: ${APP_NAME}
    triggers:
      - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: http
      port: 9080
    selector:
      app: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    port:
      targetPort: 9080
    to:
      kind: Service
      name: ${APP_NAME}
